version: '3'
services: 
  flyway:
    image: flyway/flyway
    container_name: project_dbMigration
    network_mode: host
    command: migrate -X
    volumes:
      - ./db/migration_sql:/flyway/sql
      - ./db/config/migration.conf:/flyway/conf/flyway.conf